/* generated by scripts/commercial/explode.mjs — do not edit */
export const SEQS = {
  "s1": {
    "fps": 24,
    "frames": 121
  },
  "s2": {
    "fps": 24,
    "frames": 121
  },
  "s3": {
    "fps": 24,
    "frames": 121
  },
  "s4": {
    "fps": 24,
    "frames": 121
  },
  "s5": {
    "fps": 24,
    "frames": 121
  },
  "rollcall": {
    "fps": 30,
    "frames": 98
  },
  "snap": {
    "fps": 30,
    "frames": 259
  },
  "thread": {
    "fps": 30,
    "frames": 259
  },
  "coachmeal": {
    "fps": 30,
    "frames": 300
  },
  "parenthome": {
    "fps": 30,
    "frames": 36
  },
  "ring": {
    "fps": 30,
    "frames": 175
  },
  "bfast": {
    "fps": 30,
    "frames": 228
  }
} as const;
export type SeqName = keyof typeof SEQS;
