// Explode every source mp4 into a JPEG sequence for the Remotion render.
//
// WHY: on this machine both OffthreadVideo (compositor "Request closed") and the <Video> tag
// stall the render tab after ~200 frames, whatever the concurrency. Single-frame extraction
// has always been rock-solid — so the render consumes <Img> sequences instead of video.
// Writes public/seq/<name>/0001.jpg… and src/seq-manifest.ts (fps + frame counts).
import { execFileSync } from 'node:child_process';
import { mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pub = join(here, 'remotion', 'public');
const seqRoot = join(pub, 'seq');
mkdirSync(seqRoot, { recursive: true });

// Phone-screen captures come from the 2x (--hi) takes, capped at the ~540px the composite
// actually displays (plus punch-in headroom); cinematic clips stay native.
const SOURCES = {
  s1: { max: null }, s2: { max: null }, s3: { max: null }, s4: { max: null }, s5: { max: null },
  rollcall: { max: 720, file: 'rollcall-hi.mp4' }, snap: { max: 720, file: 'snap-hi.mp4' },
  thread: { max: 720, file: 'thread-hi.mp4' }, coachmeal: { max: 720, file: 'coachmeal-hi.mp4' },
  parenthome: { max: 720, file: 'parenthome-hi.mp4' }, ring: { max: 720, file: 'ring-hi.mp4' },
  bfast: { max: 720, file: 'bfast-hi.mp4' },
  // role-demo flows (2026-07-31)
  homeday: { max: 720, file: 'homeday-hi.mp4' }, plan: { max: 720, file: 'plan-hi.mp4' },
  logsheet: { max: 720, file: 'logsheet-hi.mp4' }, checkin: { max: 720, file: 'checkin-hi.mp4' },
  progress: { max: 720, file: 'progress-hi.mp4' }, streakmove: { max: 720, file: 'streakmove-hi.mp4' },
  coachhome: { max: 720, file: 'coachhome-hi.mp4' }, roster: { max: 720, file: 'roster-hi.mp4' },
  inbox: { max: 720, file: 'inbox-hi.mp4' }, commitboard: { max: 720, file: 'commitboard-hi.mp4' },
  insights: { max: 720, file: 'insights-hi.mp4' }, announce: { max: 720, file: 'announce-hi.mp4' },
  trainerbook: { max: 720, file: 'trainerbook-hi.mp4' }, trainerhome: { max: 720, file: 'trainerhome-hi.mp4' },
  trainermeal: { max: 720, file: 'trainermeal-hi.mp4' }, trainergrow: { max: 720, file: 'trainergrow-hi.mp4' },
};

const probe = (f, entry) =>
  execFileSync('ffprobe', ['-v', 'error', '-select_streams', 'v', '-show_entries', entry, '-of', 'csv=p=0', f])
    .toString().trim();

const manifest = {};
for (const [name, { max, file }] of Object.entries(SOURCES)) {
  const src = join(pub, file || `${name}.mp4`);
  const dir = join(seqRoot, name);
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
  const rate = probe(src, 'stream=r_frame_rate');
  const [num, den] = rate.split('/').map(Number);
  const fps = num / (den || 1);
  const vf = max ? `scale='min(${max},iw)':-2` : 'null';
  execFileSync('ffmpeg', ['-y', '-loglevel', 'error', '-i', src, '-vf', vf, '-q:v', '3', join(dir, '%04d.jpg')]);
  const frames = readdirSync(dir).length;
  manifest[name] = { fps: Math.round(fps * 1000) / 1000, frames };
  console.log(`${name}: ${frames} frames @ ${fps.toFixed(2)}fps${max ? ` (≤${max}w)` : ''}`);
}

writeFileSync(join(here, 'remotion', 'src', 'seq-manifest.ts'),
  `/* generated by scripts/commercial/explode.mjs — do not edit */\n` +
  `export const SEQS = ${JSON.stringify(manifest, null, 2)} as const;\n` +
  `export type SeqName = keyof typeof SEQS;\n`);
console.log('manifest written');
