// AUTO-GENERATED by scripts/build-proto-zip.mjs — do not edit by hand.
// Content hash of assets/proto.zip; bumps whenever the proto changes so the app re-extracts.
export const PROTO_VERSION = '7bc68b89de4be20b';
