// AUTO-GENERATED by scripts/build-proto-zip.mjs — do not edit by hand.
// Content hash of assets/proto.zip; bumps whenever the proto changes so the app re-extracts.
export const PROTO_VERSION = 'a2bcd231dd9d7c97';
