// OnStandard — initial session state, ported verbatim from the prototype.
import type { AppState } from './types';
import { todayStamp } from './clock';
import { CAL_TARGET, PROTEIN_TARGET, WEIGHT_START, WEIGHT_TARGET } from './constants';
import { defaultReminderSettings } from './reminders';
import { defaultOverseerAlerts } from './overseerAlerts';
import { previewEntitlement } from './subscription';

export function createInitialState(): AppState {
  return {
    // onboarding
    flow: 'onboarding',
    obStep: 0,
    role: null,
    signinMode: false,
    athleteName: '',
    athleteEmail: '',
    orgName: '',
    level: null,
    sport: null,
    position: null,
    goals: [],
    baseHeight: 73,
    baseWeight: 178,
    baseAge: 17,
    baseGoal: 'gain',
    inviteWho: ['coach', 'parent'],
    parentFocus: ['Performance'],
    compMode: 'position',
    coachTrack: { nutrition: true, recovery: true, hydration: true, weight: true, tasks: true },

    // onboarding (redesign)
    primaryGoal: null,
    trainingFreq: null,
    supportTeam: [],
    inviteCode: '',
    teamCode: '',
    teamDiscoverable: false,
    guardianEmail: '',
    guardianStatus: 'none',
    baseNutritionConfidence: 6,
    baseMealsPerDay: 3,
    baseWaterL: 2.0,
    baseSleepH: 7,
    baseProteinFreq: 1,
    baseConsistency: 6,
    startScore: null,
    obMeta: {},

    // backend session (Phase 1 go-live, gated behind isBackendLive; inert by default)
    userId: null,
    realDataConsent: false,
    termsAcceptedAt: null,
    authError: null,
    passwordResetSent: false,
    emailConfirmPending: false,
    sharingPaused: false,
    entitlement: previewEntitlement(),
    trustPass: null,

    // day
    dateStamp: todayStamp(),
    scoreHistory: [],
    weightHistory: [],
    nutritionHistory: [],
    // Honest empty start: no fabricated PRs. The Performance screen shows a
    // "log your first result" empty state until the athlete logs one.
    perfEntries: [],
    meals: { breakfast: true, lunch: true, snack: true, dinner: false },
    mealFoods: {},
    mealLoggedAt: {},
    hydrationL: 2.4,
    quickAdded: [false, false, false],
    nudged: [],
    nudgeLog: [],
    dailyCommitment: null,
    tasks: [
      { id: 1, group: 'NUTRITION', title: 'Log breakfast', meta: '42g protein', done: true },
      { id: 2, group: null, title: 'Hit 180g protein', meta: 'protein goal', done: false },
      { id: 3, group: null, title: 'Log dinner', meta: 'Due by 8:00 PM', done: false },
      { id: 4, group: 'HYDRATION', title: 'Drink 1 gallon of water', meta: 'water goal', done: false },
      { id: 5, group: 'RECOVERY', title: '8+ hours of sleep', meta: 'Logged 8.0 hrs', done: true },
      { id: 6, group: null, title: '10 min mobility routine', meta: 'Post-practice', done: true },
    ],

    // check-in
    ciStage: 'open',
    ciWeight: 178,
    currentWeight: 178,
    weighInStamp: null,
    startWeight: WEIGHT_START,
    ciEnergy: 8,
    ciRecovery: 7,
    ciSleep: 8,
    ciConfidence: 9,
    ciSoreness: 4,
    ciMotivation: 8,
    ciSubmitted: false,
    ciConfig: { energy: true, recovery: true, sleep: true, confidence: true, soreness: false, motivation: false },

    // nav / overlays
    tab: 'home',
    coachTab: 'dashboard',
    trainerTab: 'dashboard',
    parentTab: 'overview',
    squadMode: 'team',
    cachedRoster: null,
    cachedRosterUserId: null,
    mealOpen: false,
    mealStage: 'capture',
    mealCaptureMode: 'meal',
    mealType: 'Dinner',
    mealAnalysis: null,
    mealQuestions: [],
    mealError: null,
    labelFacts: null,
    labelServings: 1,
    mealPhoto: null,
    mealDetailOpen: false,
    overseerProfileOpen: false,
    plansOpen: false,
    coachGoalsOpen: false,
    mealHistoryOpen: false,
    nutritionMemoryOpen: false,
    mealHistory: null,
    foodCoachOpen: false,
    planEditorOpen: false,
    selectedMeal: null,
    notifOpen: false,
    personDetail: null,
    accountOpen: false,
    msgOpen: false,
    connectOpen: false,
    connectPrefillCode: null,
    connectCardDismissed: false,
    notifications: [],

    // misc
    weeklyGoalLb: 1.0,
    proteinTarget: PROTEIN_TARGET,
    calTarget: CAL_TARGET,
    planInstructions: [],
    planSlots: [],
    weightTarget: WEIGHT_TARGET,
    visibility: 'parent',
    notif: true,
    reminderSettings: defaultReminderSettings(),
    overseerAlerts: defaultOverseerAlerts(),
    units: 'imperial',
    themeMode: 'auto',
    mealDesc: '',
    chatDraft: '',
    msgDraft: '',

    // chat / memory
    coachNote: 'Ease up on refined carbs at dinner. Swap bread for rice or sweet potato.',
    mealChat: [
      { who: 'ai', text: 'Detected grilled chicken, brown rice & broccoli. Quality 94. Strong protein, clean carbs, good timing.' },
      { who: 'coach', text: 'Great plate. Ease up on the rice portion at night though, and keep carbs earlier in the day.' },
      { who: 'ai', text: 'Noted. I’ll flag smaller dinner carbs on Jihad’s plan and remind him going forward.' },
    ],
    msgThread: [
      { who: 'them', text: 'Thanks for staying on top of this. It really helps to see the daily numbers.' },
      { who: 'me', text: 'Of course. I’ll flag anything that looks off this week.' },
    ],
  };
}
