// AthleteOS core — pure, framework-agnostic domain logic.
// Designed to lift into a shared `packages/core` when the desktop dashboards land.
export * from './types';
export * from './constants';
export * from './scoring';
export * from './startingScore';
export * from './recommendation';
export * from './leaderboard';
export * from './content';
export * from './coaching';
export * from './units';
export * from './contrast';
export * from './history';
export * from './performance';
export * from './person';
export * from './attention';
export * from './roster';
export * from './rosterSync';
export * from './mealEdit';
export * from './foodDb';
export * from './reminders';
export * from './weeklyReport';
export * from './consent';
export * from './nudge';
export * from './identity';
export * from './account';
export * from './validate';
export * from './dayRollover';
export * from './clock';
export { createInitialState } from './defaultState';
