#!/usr/bin/env node
// OnStandard — bulk school directory importer.
//
// Turns an official public-domain roster CSV into a seed migration for the `orgs` table,
// so the school picker (0022_schools.sql) is backed by the real national list instead of
// the small starter seed. Licensing: NCES (public K-12 schools) and IPEDS (colleges) are
// U.S. Department of Education PUBLIC DOMAIN data — free to bundle, no attribution required.
//
// Usage:
//   1. Download a roster CSV, e.g.:
//        • NCES public schools:  https://nces.ed.gov/ccd/files.asp  (Directory file)
//        • IPEDS colleges:       https://nces.ed.gov/ipeds/datacenter/  (HD institutions)
//   2. node scripts/import-schools.mjs <path-to.csv> [--type=school] [--out=supabase/migrations/0026_schools_bulk.sql]
//   3. Review the generated migration, then `supabase db push`.
//
// The script auto-detects common NCES/IPEDS column names (SCH_NAME/INSTNM, LCITY/CITY,
// LSTATE/STABBR) or generic name/city/state headers, dedupes case-insensitively on
// (name, state), escapes quotes, and batches INSERTs. Rows already present are skipped by
// a NOT EXISTS guard so re-running / partial imports are safe.
import { readFileSync, writeFileSync } from 'node:fs';

const args = process.argv.slice(2);
const csvPath = args.find((a) => !a.startsWith('--'));
const type = (args.find((a) => a.startsWith('--type=')) ?? '--type=school').split('=')[1];
const outPath = (args.find((a) => a.startsWith('--out=')) ?? '--out=supabase/migrations/0026_schools_bulk.sql').split('=')[1];

if (!csvPath) {
  console.error('Usage: node scripts/import-schools.mjs <roster.csv> [--type=school|club] [--out=path.sql]');
  process.exit(1);
}

/** Minimal RFC-4180 CSV parser (handles quoted fields with commas / escaped quotes). */
function parseCsv(text) {
  const rows = [];
  let row = [], field = '', inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (inQuotes) {
      if (ch === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; } else { inQuotes = false; }
      } else field += ch;
    } else if (ch === '"') inQuotes = true;
    else if (ch === ',') { row.push(field); field = ''; }
    else if (ch === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else if (ch !== '\r') field += ch;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows;
}

const raw = readFileSync(csvPath, 'utf8');
const rows = parseCsv(raw).filter((r) => r.length > 1);
if (rows.length < 2) { console.error('CSV looks empty.'); process.exit(1); }

const header = rows[0].map((h) => h.trim().toLowerCase());
const pick = (...names) => header.findIndex((h) => names.includes(h));
const nameIdx = pick('sch_name', 'instnm', 'name', 'school', 'school_name');
const cityIdx = pick('lcity', 'city', 'lcity09');
const stateIdx = pick('lstate', 'stabbr', 'state', 'st');
if (nameIdx < 0) { console.error(`Could not find a name column. Headers: ${header.join(', ')}`); process.exit(1); }

const seen = new Set();
const values = [];
for (const r of rows.slice(1)) {
  const name = (r[nameIdx] ?? '').trim();
  if (!name) continue;
  const city = cityIdx >= 0 ? (r[cityIdx] ?? '').trim() : '';
  const state = stateIdx >= 0 ? (r[stateIdx] ?? '').trim() : '';
  const key = `${name.toLowerCase()}|${state.toLowerCase()}`;
  if (seen.has(key)) continue;
  seen.add(key);
  const esc = (s) => (s ? `'${s.replace(/'/g, "''")}'` : 'null');
  values.push(`  (${esc(name)}, '${type}', ${esc(city)}, ${esc(state)})`);
}

const BATCH = 1000;
let sql = `-- OnStandard — bulk school directory seed (generated by scripts/import-schools.mjs)\n` +
  `-- Source: ${csvPath} · ${values.length} unique orgs · public-domain (NCES/IPEDS).\n` +
  `-- Skips rows already present (NOT EXISTS on lower(name)+lower(state)), so it is safe to\n` +
  `-- re-run and it won't duplicate the 0022 starter seed. Apply after 0022_schools.sql.\n\n`;
for (let i = 0; i < values.length; i += BATCH) {
  const batch = values.slice(i, i + BATCH);
  sql += `insert into orgs (name, type, city, state)\nselect v.name, v.type::org_type, v.city, v.state from (values\n` +
    batch.join(',\n') +
    `\n) as v(name, type, city, state)\nwhere not exists (\n` +
    `  select 1 from orgs o where lower(o.name) = lower(v.name)\n` +
    `    and lower(coalesce(o.state,'')) = lower(coalesce(v.state,''))\n);\n\n`;
}

writeFileSync(outPath, sql);
console.log(`Wrote ${values.length} unique schools to ${outPath} (${Math.ceil(values.length / BATCH)} batch(es)).`);
console.log('Review it, then: supabase db push');
