-- OnStandard — 0057 org directory seed
--
-- Seeds the org directory (`orgs`) with:
--   * Every NCAA Division I school (FBS + FCS + non-football D1, 2025-26 membership)
--     as type='school', level='college', league='NCAA D1'
--   * All current major US/Canada pro franchises: 32 NFL, 30 NBA, 30 MLB, 32 NHL,
--     30 MLS (San Diego FC joined MLS in 2025, so the league is 30 clubs, not 29)
--     as type='club', level='pro', league='NFL'|'NBA'|'MLB'|'NHL'|'MLS'
--
-- These rows are UNCLAIMED, system-owned directory entries (created_by is null).
-- Selecting one during onboarding does NOT grant any access — joining a team on
-- an org still requires the coach's join code or an approved join request, exactly
-- as before. The directory only makes sure athlete and coach land on the SAME org.
--
-- Idempotency: a partial UNIQUE index on (lower(name), coalesce(state,'')) scoped
-- to created_by IS NULL (seed rows only) backs `insert ... on conflict do nothing`,
-- so re-running this migration is a no-op and it can never collide with or modify
-- user-created org rows (those have created_by set and sit outside the index).
-- The five universities already seeded by 0022 use the same names/states here, so
-- they dedupe cleanly instead of duplicating.
--
-- Note: orgs.created_by has been nullable since 0001 (`references profiles(id)
-- on delete set null`), so no `drop not null` is required for these system rows.
-- 0022 already added orgs.city / orgs.state and the (non-unique) search index.
--
-- GUARDRAIL: authored by direction of the founder 2026-07-14; apply with supabase db push.

-- ---------------------------------------------------------------- new columns
-- level: coarse competition tier used by directory filters/badges.
alter table orgs add column if not exists level text
  check (level is null or level in ('hs','college','pro','club'));

-- league: display label for the governing league ('NCAA D1','NFL','NBA','MLB','NHL','MLS').
alter table orgs add column if not exists league text;

-- ---------------------------------------------------------------- idempotency guard
-- Partial unique index over seed rows only (created_by is null). User-created orgs
-- (created_by set) are untouched by both the index and the on-conflict clauses below.
create unique index if not exists orgs_directory_seed_unique
  on orgs (lower(name), coalesce(state, ''))
  where created_by is null;

-- ================================================================ NCAA D1 — FBS (136)
insert into orgs (name, type, city, state, level, league) values
  -- SEC
  ('University of Alabama', 'school', 'Tuscaloosa', 'AL', 'college', 'NCAA D1'),
  ('University of Arkansas', 'school', 'Fayetteville', 'AR', 'college', 'NCAA D1'),
  ('Auburn University', 'school', 'Auburn', 'AL', 'college', 'NCAA D1'),
  ('University of Florida', 'school', 'Gainesville', 'FL', 'college', 'NCAA D1'),
  ('University of Georgia', 'school', 'Athens', 'GA', 'college', 'NCAA D1'),
  ('University of Kentucky', 'school', 'Lexington', 'KY', 'college', 'NCAA D1'),
  ('Louisiana State University', 'school', 'Baton Rouge', 'LA', 'college', 'NCAA D1'),
  ('University of Mississippi', 'school', 'Oxford', 'MS', 'college', 'NCAA D1'),
  ('Mississippi State University', 'school', 'Starkville', 'MS', 'college', 'NCAA D1'),
  ('University of Missouri', 'school', 'Columbia', 'MO', 'college', 'NCAA D1'),
  ('University of Oklahoma', 'school', 'Norman', 'OK', 'college', 'NCAA D1'),
  ('University of South Carolina', 'school', 'Columbia', 'SC', 'college', 'NCAA D1'),
  ('University of Tennessee', 'school', 'Knoxville', 'TN', 'college', 'NCAA D1'),
  ('University of Texas at Austin', 'school', 'Austin', 'TX', 'college', 'NCAA D1'),
  ('Texas A&M University', 'school', 'College Station', 'TX', 'college', 'NCAA D1'),
  ('Vanderbilt University', 'school', 'Nashville', 'TN', 'college', 'NCAA D1'),
  -- Big Ten
  ('University of Illinois Urbana-Champaign', 'school', 'Champaign', 'IL', 'college', 'NCAA D1'),
  ('Indiana University', 'school', 'Bloomington', 'IN', 'college', 'NCAA D1'),
  ('University of Iowa', 'school', 'Iowa City', 'IA', 'college', 'NCAA D1'),
  ('University of Maryland', 'school', 'College Park', 'MD', 'college', 'NCAA D1'),
  ('University of Michigan', 'school', 'Ann Arbor', 'MI', 'college', 'NCAA D1'),
  ('Michigan State University', 'school', 'East Lansing', 'MI', 'college', 'NCAA D1'),
  ('University of Minnesota', 'school', 'Minneapolis', 'MN', 'college', 'NCAA D1'),
  ('University of Nebraska-Lincoln', 'school', 'Lincoln', 'NE', 'college', 'NCAA D1'),
  ('Northwestern University', 'school', 'Evanston', 'IL', 'college', 'NCAA D1'),
  ('Ohio State University', 'school', 'Columbus', 'OH', 'college', 'NCAA D1'),
  ('University of Oregon', 'school', 'Eugene', 'OR', 'college', 'NCAA D1'),
  ('Pennsylvania State University', 'school', 'University Park', 'PA', 'college', 'NCAA D1'),
  ('Purdue University', 'school', 'West Lafayette', 'IN', 'college', 'NCAA D1'),
  ('Rutgers University', 'school', 'Piscataway', 'NJ', 'college', 'NCAA D1'),
  ('University of California, Los Angeles', 'school', 'Los Angeles', 'CA', 'college', 'NCAA D1'),
  ('University of Southern California', 'school', 'Los Angeles', 'CA', 'college', 'NCAA D1'),
  ('University of Washington', 'school', 'Seattle', 'WA', 'college', 'NCAA D1'),
  ('University of Wisconsin-Madison', 'school', 'Madison', 'WI', 'college', 'NCAA D1'),
  -- Big 12
  ('University of Arizona', 'school', 'Tucson', 'AZ', 'college', 'NCAA D1'),
  ('Arizona State University', 'school', 'Tempe', 'AZ', 'college', 'NCAA D1'),
  ('Baylor University', 'school', 'Waco', 'TX', 'college', 'NCAA D1'),
  ('Brigham Young University', 'school', 'Provo', 'UT', 'college', 'NCAA D1'),
  ('University of Central Florida', 'school', 'Orlando', 'FL', 'college', 'NCAA D1'),
  ('University of Cincinnati', 'school', 'Cincinnati', 'OH', 'college', 'NCAA D1'),
  ('University of Colorado Boulder', 'school', 'Boulder', 'CO', 'college', 'NCAA D1'),
  ('University of Houston', 'school', 'Houston', 'TX', 'college', 'NCAA D1'),
  ('Iowa State University', 'school', 'Ames', 'IA', 'college', 'NCAA D1'),
  ('University of Kansas', 'school', 'Lawrence', 'KS', 'college', 'NCAA D1'),
  ('Kansas State University', 'school', 'Manhattan', 'KS', 'college', 'NCAA D1'),
  ('Oklahoma State University', 'school', 'Stillwater', 'OK', 'college', 'NCAA D1'),
  ('Texas Christian University', 'school', 'Fort Worth', 'TX', 'college', 'NCAA D1'),
  ('Texas Tech University', 'school', 'Lubbock', 'TX', 'college', 'NCAA D1'),
  ('University of Utah', 'school', 'Salt Lake City', 'UT', 'college', 'NCAA D1'),
  ('West Virginia University', 'school', 'Morgantown', 'WV', 'college', 'NCAA D1'),
  -- ACC
  ('Boston College', 'school', 'Chestnut Hill', 'MA', 'college', 'NCAA D1'),
  ('University of California, Berkeley', 'school', 'Berkeley', 'CA', 'college', 'NCAA D1'),
  ('Clemson University', 'school', 'Clemson', 'SC', 'college', 'NCAA D1'),
  ('Duke University', 'school', 'Durham', 'NC', 'college', 'NCAA D1'),
  ('Florida State University', 'school', 'Tallahassee', 'FL', 'college', 'NCAA D1'),
  ('Georgia Institute of Technology', 'school', 'Atlanta', 'GA', 'college', 'NCAA D1'),
  ('University of Louisville', 'school', 'Louisville', 'KY', 'college', 'NCAA D1'),
  ('University of Miami', 'school', 'Coral Gables', 'FL', 'college', 'NCAA D1'),
  ('University of North Carolina at Chapel Hill', 'school', 'Chapel Hill', 'NC', 'college', 'NCAA D1'),
  ('North Carolina State University', 'school', 'Raleigh', 'NC', 'college', 'NCAA D1'),
  ('University of Pittsburgh', 'school', 'Pittsburgh', 'PA', 'college', 'NCAA D1'),
  ('Southern Methodist University', 'school', 'Dallas', 'TX', 'college', 'NCAA D1'),
  ('Stanford University', 'school', 'Stanford', 'CA', 'college', 'NCAA D1'),
  ('Syracuse University', 'school', 'Syracuse', 'NY', 'college', 'NCAA D1'),
  ('University of Virginia', 'school', 'Charlottesville', 'VA', 'college', 'NCAA D1'),
  ('Virginia Tech', 'school', 'Blacksburg', 'VA', 'college', 'NCAA D1'),
  ('Wake Forest University', 'school', 'Winston-Salem', 'NC', 'college', 'NCAA D1'),
  -- Pac-12
  ('Oregon State University', 'school', 'Corvallis', 'OR', 'college', 'NCAA D1'),
  ('Washington State University', 'school', 'Pullman', 'WA', 'college', 'NCAA D1'),
  -- American
  ('United States Military Academy', 'school', 'West Point', 'NY', 'college', 'NCAA D1'),
  ('University of North Carolina at Charlotte', 'school', 'Charlotte', 'NC', 'college', 'NCAA D1'),
  ('East Carolina University', 'school', 'Greenville', 'NC', 'college', 'NCAA D1'),
  ('Florida Atlantic University', 'school', 'Boca Raton', 'FL', 'college', 'NCAA D1'),
  ('University of Memphis', 'school', 'Memphis', 'TN', 'college', 'NCAA D1'),
  ('United States Naval Academy', 'school', 'Annapolis', 'MD', 'college', 'NCAA D1'),
  ('University of North Texas', 'school', 'Denton', 'TX', 'college', 'NCAA D1'),
  ('Rice University', 'school', 'Houston', 'TX', 'college', 'NCAA D1'),
  ('University of South Florida', 'school', 'Tampa', 'FL', 'college', 'NCAA D1'),
  ('Temple University', 'school', 'Philadelphia', 'PA', 'college', 'NCAA D1'),
  ('Tulane University', 'school', 'New Orleans', 'LA', 'college', 'NCAA D1'),
  ('University of Tulsa', 'school', 'Tulsa', 'OK', 'college', 'NCAA D1'),
  ('University of Alabama at Birmingham', 'school', 'Birmingham', 'AL', 'college', 'NCAA D1'),
  ('University of Texas at San Antonio', 'school', 'San Antonio', 'TX', 'college', 'NCAA D1'),
  -- Conference USA
  ('University of Delaware', 'school', 'Newark', 'DE', 'college', 'NCAA D1'),
  ('Florida International University', 'school', 'Miami', 'FL', 'college', 'NCAA D1'),
  ('Jacksonville State University', 'school', 'Jacksonville', 'AL', 'college', 'NCAA D1'),
  ('Kennesaw State University', 'school', 'Kennesaw', 'GA', 'college', 'NCAA D1'),
  ('Liberty University', 'school', 'Lynchburg', 'VA', 'college', 'NCAA D1'),
  ('Louisiana Tech University', 'school', 'Ruston', 'LA', 'college', 'NCAA D1'),
  ('Middle Tennessee State University', 'school', 'Murfreesboro', 'TN', 'college', 'NCAA D1'),
  ('Missouri State University', 'school', 'Springfield', 'MO', 'college', 'NCAA D1'),
  ('New Mexico State University', 'school', 'Las Cruces', 'NM', 'college', 'NCAA D1'),
  ('Sam Houston State University', 'school', 'Huntsville', 'TX', 'college', 'NCAA D1'),
  ('University of Texas at El Paso', 'school', 'El Paso', 'TX', 'college', 'NCAA D1'),
  ('Western Kentucky University', 'school', 'Bowling Green', 'KY', 'college', 'NCAA D1'),
  -- MAC
  ('University of Akron', 'school', 'Akron', 'OH', 'college', 'NCAA D1'),
  ('Ball State University', 'school', 'Muncie', 'IN', 'college', 'NCAA D1'),
  ('Bowling Green State University', 'school', 'Bowling Green', 'OH', 'college', 'NCAA D1'),
  ('University at Buffalo', 'school', 'Buffalo', 'NY', 'college', 'NCAA D1'),
  ('Central Michigan University', 'school', 'Mount Pleasant', 'MI', 'college', 'NCAA D1'),
  ('Eastern Michigan University', 'school', 'Ypsilanti', 'MI', 'college', 'NCAA D1'),
  ('Kent State University', 'school', 'Kent', 'OH', 'college', 'NCAA D1'),
  ('University of Massachusetts Amherst', 'school', 'Amherst', 'MA', 'college', 'NCAA D1'),
  ('Miami University', 'school', 'Oxford', 'OH', 'college', 'NCAA D1'),
  ('Northern Illinois University', 'school', 'DeKalb', 'IL', 'college', 'NCAA D1'),
  ('Ohio University', 'school', 'Athens', 'OH', 'college', 'NCAA D1'),
  ('University of Toledo', 'school', 'Toledo', 'OH', 'college', 'NCAA D1'),
  ('Western Michigan University', 'school', 'Kalamazoo', 'MI', 'college', 'NCAA D1'),
  -- Mountain West
  ('United States Air Force Academy', 'school', 'Colorado Springs', 'CO', 'college', 'NCAA D1'),
  ('Boise State University', 'school', 'Boise', 'ID', 'college', 'NCAA D1'),
  ('Colorado State University', 'school', 'Fort Collins', 'CO', 'college', 'NCAA D1'),
  ('Fresno State University', 'school', 'Fresno', 'CA', 'college', 'NCAA D1'),
  ('University of Hawaii at Manoa', 'school', 'Honolulu', 'HI', 'college', 'NCAA D1'),
  ('University of Nevada, Reno', 'school', 'Reno', 'NV', 'college', 'NCAA D1'),
  ('University of New Mexico', 'school', 'Albuquerque', 'NM', 'college', 'NCAA D1'),
  ('San Diego State University', 'school', 'San Diego', 'CA', 'college', 'NCAA D1'),
  ('San Jose State University', 'school', 'San Jose', 'CA', 'college', 'NCAA D1'),
  ('University of Nevada, Las Vegas', 'school', 'Las Vegas', 'NV', 'college', 'NCAA D1'),
  ('Utah State University', 'school', 'Logan', 'UT', 'college', 'NCAA D1'),
  ('University of Wyoming', 'school', 'Laramie', 'WY', 'college', 'NCAA D1'),
  -- Sun Belt
  ('Appalachian State University', 'school', 'Boone', 'NC', 'college', 'NCAA D1'),
  ('Arkansas State University', 'school', 'Jonesboro', 'AR', 'college', 'NCAA D1'),
  ('Coastal Carolina University', 'school', 'Conway', 'SC', 'college', 'NCAA D1'),
  ('Georgia Southern University', 'school', 'Statesboro', 'GA', 'college', 'NCAA D1'),
  ('Georgia State University', 'school', 'Atlanta', 'GA', 'college', 'NCAA D1'),
  ('James Madison University', 'school', 'Harrisonburg', 'VA', 'college', 'NCAA D1'),
  ('University of Louisiana at Lafayette', 'school', 'Lafayette', 'LA', 'college', 'NCAA D1'),
  ('University of Louisiana at Monroe', 'school', 'Monroe', 'LA', 'college', 'NCAA D1'),
  ('Marshall University', 'school', 'Huntington', 'WV', 'college', 'NCAA D1'),
  ('Old Dominion University', 'school', 'Norfolk', 'VA', 'college', 'NCAA D1'),
  ('University of South Alabama', 'school', 'Mobile', 'AL', 'college', 'NCAA D1'),
  ('University of Southern Mississippi', 'school', 'Hattiesburg', 'MS', 'college', 'NCAA D1'),
  ('Texas State University', 'school', 'San Marcos', 'TX', 'college', 'NCAA D1'),
  ('Troy University', 'school', 'Troy', 'AL', 'college', 'NCAA D1'),
  -- FBS independents
  ('University of Notre Dame', 'school', 'Notre Dame', 'IN', 'college', 'NCAA D1'),
  ('University of Connecticut', 'school', 'Storrs', 'CT', 'college', 'NCAA D1')
on conflict ((lower(name)), (coalesce(state, ''))) where created_by is null do nothing;

-- ================================================================ NCAA D1 — FCS (129)
insert into orgs (name, type, city, state, level, league) values
  -- Big Sky
  ('California Polytechnic State University', 'school', 'San Luis Obispo', 'CA', 'college', 'NCAA D1'),
  ('Eastern Washington University', 'school', 'Cheney', 'WA', 'college', 'NCAA D1'),
  ('University of Idaho', 'school', 'Moscow', 'ID', 'college', 'NCAA D1'),
  ('Idaho State University', 'school', 'Pocatello', 'ID', 'college', 'NCAA D1'),
  ('University of Montana', 'school', 'Missoula', 'MT', 'college', 'NCAA D1'),
  ('Montana State University', 'school', 'Bozeman', 'MT', 'college', 'NCAA D1'),
  ('Northern Arizona University', 'school', 'Flagstaff', 'AZ', 'college', 'NCAA D1'),
  ('University of Northern Colorado', 'school', 'Greeley', 'CO', 'college', 'NCAA D1'),
  ('Portland State University', 'school', 'Portland', 'OR', 'college', 'NCAA D1'),
  ('Sacramento State University', 'school', 'Sacramento', 'CA', 'college', 'NCAA D1'),
  ('University of California, Davis', 'school', 'Davis', 'CA', 'college', 'NCAA D1'),
  ('Weber State University', 'school', 'Ogden', 'UT', 'college', 'NCAA D1'),
  -- Big South-OVC
  ('Charleston Southern University', 'school', 'Charleston', 'SC', 'college', 'NCAA D1'),
  ('Eastern Illinois University', 'school', 'Charleston', 'IL', 'college', 'NCAA D1'),
  ('Gardner-Webb University', 'school', 'Boiling Springs', 'NC', 'college', 'NCAA D1'),
  ('Lindenwood University', 'school', 'St. Charles', 'MO', 'college', 'NCAA D1'),
  ('Southeast Missouri State University', 'school', 'Cape Girardeau', 'MO', 'college', 'NCAA D1'),
  ('Tennessee State University', 'school', 'Nashville', 'TN', 'college', 'NCAA D1'),
  ('Tennessee Tech University', 'school', 'Cookeville', 'TN', 'college', 'NCAA D1'),
  ('University of Tennessee at Martin', 'school', 'Martin', 'TN', 'college', 'NCAA D1'),
  ('Western Illinois University', 'school', 'Macomb', 'IL', 'college', 'NCAA D1'),
  -- CAA Football
  ('University at Albany', 'school', 'Albany', 'NY', 'college', 'NCAA D1'),
  ('Bryant University', 'school', 'Smithfield', 'RI', 'college', 'NCAA D1'),
  ('Campbell University', 'school', 'Buies Creek', 'NC', 'college', 'NCAA D1'),
  ('Elon University', 'school', 'Elon', 'NC', 'college', 'NCAA D1'),
  ('Hampton University', 'school', 'Hampton', 'VA', 'college', 'NCAA D1'),
  ('University of Maine', 'school', 'Orono', 'ME', 'college', 'NCAA D1'),
  ('Monmouth University', 'school', 'West Long Branch', 'NJ', 'college', 'NCAA D1'),
  ('University of New Hampshire', 'school', 'Durham', 'NH', 'college', 'NCAA D1'),
  ('North Carolina A&T State University', 'school', 'Greensboro', 'NC', 'college', 'NCAA D1'),
  ('University of Rhode Island', 'school', 'Kingston', 'RI', 'college', 'NCAA D1'),
  ('University of Richmond', 'school', 'Richmond', 'VA', 'college', 'NCAA D1'),
  ('Stony Brook University', 'school', 'Stony Brook', 'NY', 'college', 'NCAA D1'),
  ('Towson University', 'school', 'Towson', 'MD', 'college', 'NCAA D1'),
  ('Villanova University', 'school', 'Villanova', 'PA', 'college', 'NCAA D1'),
  ('College of William & Mary', 'school', 'Williamsburg', 'VA', 'college', 'NCAA D1'),
  -- Ivy League
  ('Brown University', 'school', 'Providence', 'RI', 'college', 'NCAA D1'),
  ('Columbia University', 'school', 'New York', 'NY', 'college', 'NCAA D1'),
  ('Cornell University', 'school', 'Ithaca', 'NY', 'college', 'NCAA D1'),
  ('Dartmouth College', 'school', 'Hanover', 'NH', 'college', 'NCAA D1'),
  ('Harvard University', 'school', 'Cambridge', 'MA', 'college', 'NCAA D1'),
  ('University of Pennsylvania', 'school', 'Philadelphia', 'PA', 'college', 'NCAA D1'),
  ('Princeton University', 'school', 'Princeton', 'NJ', 'college', 'NCAA D1'),
  ('Yale University', 'school', 'New Haven', 'CT', 'college', 'NCAA D1'),
  -- MEAC (football)
  ('Delaware State University', 'school', 'Dover', 'DE', 'college', 'NCAA D1'),
  ('Howard University', 'school', 'Washington', 'DC', 'college', 'NCAA D1'),
  ('Morgan State University', 'school', 'Baltimore', 'MD', 'college', 'NCAA D1'),
  ('Norfolk State University', 'school', 'Norfolk', 'VA', 'college', 'NCAA D1'),
  ('North Carolina Central University', 'school', 'Durham', 'NC', 'college', 'NCAA D1'),
  ('South Carolina State University', 'school', 'Orangeburg', 'SC', 'college', 'NCAA D1'),
  -- Missouri Valley Football
  ('Illinois State University', 'school', 'Normal', 'IL', 'college', 'NCAA D1'),
  ('Indiana State University', 'school', 'Terre Haute', 'IN', 'college', 'NCAA D1'),
  ('Murray State University', 'school', 'Murray', 'KY', 'college', 'NCAA D1'),
  ('University of North Dakota', 'school', 'Grand Forks', 'ND', 'college', 'NCAA D1'),
  ('North Dakota State University', 'school', 'Fargo', 'ND', 'college', 'NCAA D1'),
  ('University of Northern Iowa', 'school', 'Cedar Falls', 'IA', 'college', 'NCAA D1'),
  ('University of South Dakota', 'school', 'Vermillion', 'SD', 'college', 'NCAA D1'),
  ('South Dakota State University', 'school', 'Brookings', 'SD', 'college', 'NCAA D1'),
  ('Southern Illinois University', 'school', 'Carbondale', 'IL', 'college', 'NCAA D1'),
  ('Youngstown State University', 'school', 'Youngstown', 'OH', 'college', 'NCAA D1'),
  -- Northeast Conference (football)
  ('Central Connecticut State University', 'school', 'New Britain', 'CT', 'college', 'NCAA D1'),
  ('Duquesne University', 'school', 'Pittsburgh', 'PA', 'college', 'NCAA D1'),
  ('Long Island University', 'school', 'Brookville', 'NY', 'college', 'NCAA D1'),
  ('Mercyhurst University', 'school', 'Erie', 'PA', 'college', 'NCAA D1'),
  ('Robert Morris University', 'school', 'Moon Township', 'PA', 'college', 'NCAA D1'),
  ('Saint Francis University', 'school', 'Loretto', 'PA', 'college', 'NCAA D1'),
  ('Stonehill College', 'school', 'Easton', 'MA', 'college', 'NCAA D1'),
  ('Wagner College', 'school', 'Staten Island', 'NY', 'college', 'NCAA D1'),
  ('University of New Haven', 'school', 'West Haven', 'CT', 'college', 'NCAA D1'),
  -- Patriot League (football)
  ('Bucknell University', 'school', 'Lewisburg', 'PA', 'college', 'NCAA D1'),
  ('Colgate University', 'school', 'Hamilton', 'NY', 'college', 'NCAA D1'),
  ('Fordham University', 'school', 'Bronx', 'NY', 'college', 'NCAA D1'),
  ('Georgetown University', 'school', 'Washington', 'DC', 'college', 'NCAA D1'),
  ('College of the Holy Cross', 'school', 'Worcester', 'MA', 'college', 'NCAA D1'),
  ('Lafayette College', 'school', 'Easton', 'PA', 'college', 'NCAA D1'),
  ('Lehigh University', 'school', 'Bethlehem', 'PA', 'college', 'NCAA D1'),
  -- Pioneer Football League
  ('Butler University', 'school', 'Indianapolis', 'IN', 'college', 'NCAA D1'),
  ('Davidson College', 'school', 'Davidson', 'NC', 'college', 'NCAA D1'),
  ('University of Dayton', 'school', 'Dayton', 'OH', 'college', 'NCAA D1'),
  ('Drake University', 'school', 'Des Moines', 'IA', 'college', 'NCAA D1'),
  ('Marist College', 'school', 'Poughkeepsie', 'NY', 'college', 'NCAA D1'),
  ('Morehead State University', 'school', 'Morehead', 'KY', 'college', 'NCAA D1'),
  ('Presbyterian College', 'school', 'Clinton', 'SC', 'college', 'NCAA D1'),
  ('University of San Diego', 'school', 'San Diego', 'CA', 'college', 'NCAA D1'),
  ('University of St. Thomas', 'school', 'St. Paul', 'MN', 'college', 'NCAA D1'),
  ('Stetson University', 'school', 'DeLand', 'FL', 'college', 'NCAA D1'),
  ('Valparaiso University', 'school', 'Valparaiso', 'IN', 'college', 'NCAA D1'),
  -- Southern Conference (football)
  ('University of Tennessee at Chattanooga', 'school', 'Chattanooga', 'TN', 'college', 'NCAA D1'),
  ('The Citadel', 'school', 'Charleston', 'SC', 'college', 'NCAA D1'),
  ('East Tennessee State University', 'school', 'Johnson City', 'TN', 'college', 'NCAA D1'),
  ('Furman University', 'school', 'Greenville', 'SC', 'college', 'NCAA D1'),
  ('Mercer University', 'school', 'Macon', 'GA', 'college', 'NCAA D1'),
  ('Samford University', 'school', 'Birmingham', 'AL', 'college', 'NCAA D1'),
  ('Virginia Military Institute', 'school', 'Lexington', 'VA', 'college', 'NCAA D1'),
  ('Western Carolina University', 'school', 'Cullowhee', 'NC', 'college', 'NCAA D1'),
  ('Wofford College', 'school', 'Spartanburg', 'SC', 'college', 'NCAA D1'),
  -- Southland (football)
  ('Houston Christian University', 'school', 'Houston', 'TX', 'college', 'NCAA D1'),
  ('University of the Incarnate Word', 'school', 'San Antonio', 'TX', 'college', 'NCAA D1'),
  ('Lamar University', 'school', 'Beaumont', 'TX', 'college', 'NCAA D1'),
  ('McNeese State University', 'school', 'Lake Charles', 'LA', 'college', 'NCAA D1'),
  ('Nicholls State University', 'school', 'Thibodaux', 'LA', 'college', 'NCAA D1'),
  ('Northwestern State University', 'school', 'Natchitoches', 'LA', 'college', 'NCAA D1'),
  ('Southeastern Louisiana University', 'school', 'Hammond', 'LA', 'college', 'NCAA D1'),
  ('Stephen F. Austin State University', 'school', 'Nacogdoches', 'TX', 'college', 'NCAA D1'),
  ('East Texas A&M University', 'school', 'Commerce', 'TX', 'college', 'NCAA D1'),
  ('University of Texas Rio Grande Valley', 'school', 'Edinburg', 'TX', 'college', 'NCAA D1'),
  -- SWAC
  ('Alabama A&M University', 'school', 'Huntsville', 'AL', 'college', 'NCAA D1'),
  ('Alabama State University', 'school', 'Montgomery', 'AL', 'college', 'NCAA D1'),
  ('Alcorn State University', 'school', 'Lorman', 'MS', 'college', 'NCAA D1'),
  ('University of Arkansas at Pine Bluff', 'school', 'Pine Bluff', 'AR', 'college', 'NCAA D1'),
  ('Bethune-Cookman University', 'school', 'Daytona Beach', 'FL', 'college', 'NCAA D1'),
  ('Florida A&M University', 'school', 'Tallahassee', 'FL', 'college', 'NCAA D1'),
  ('Grambling State University', 'school', 'Grambling', 'LA', 'college', 'NCAA D1'),
  ('Jackson State University', 'school', 'Jackson', 'MS', 'college', 'NCAA D1'),
  ('Mississippi Valley State University', 'school', 'Itta Bena', 'MS', 'college', 'NCAA D1'),
  ('Prairie View A&M University', 'school', 'Prairie View', 'TX', 'college', 'NCAA D1'),
  ('Southern University', 'school', 'Baton Rouge', 'LA', 'college', 'NCAA D1'),
  ('Texas Southern University', 'school', 'Houston', 'TX', 'college', 'NCAA D1'),
  -- United Athletic Conference
  ('Abilene Christian University', 'school', 'Abilene', 'TX', 'college', 'NCAA D1'),
  ('Austin Peay State University', 'school', 'Clarksville', 'TN', 'college', 'NCAA D1'),
  ('University of Central Arkansas', 'school', 'Conway', 'AR', 'college', 'NCAA D1'),
  ('Eastern Kentucky University', 'school', 'Richmond', 'KY', 'college', 'NCAA D1'),
  ('University of North Alabama', 'school', 'Florence', 'AL', 'college', 'NCAA D1'),
  ('Southern Utah University', 'school', 'Cedar City', 'UT', 'college', 'NCAA D1'),
  ('Tarleton State University', 'school', 'Stephenville', 'TX', 'college', 'NCAA D1'),
  ('Utah Tech University', 'school', 'St. George', 'UT', 'college', 'NCAA D1'),
  ('University of West Georgia', 'school', 'Carrollton', 'GA', 'college', 'NCAA D1'),
  -- FCS independents
  ('Sacred Heart University', 'school', 'Fairfield', 'CT', 'college', 'NCAA D1'),
  ('Merrimack College', 'school', 'North Andover', 'MA', 'college', 'NCAA D1')
on conflict ((lower(name)), (coalesce(state, ''))) where created_by is null do nothing;

-- ================================================================ NCAA D1 — non-football (99)
insert into orgs (name, type, city, state, level, league) values
  -- Big East
  ('Creighton University', 'school', 'Omaha', 'NE', 'college', 'NCAA D1'),
  ('DePaul University', 'school', 'Chicago', 'IL', 'college', 'NCAA D1'),
  ('Marquette University', 'school', 'Milwaukee', 'WI', 'college', 'NCAA D1'),
  ('Providence College', 'school', 'Providence', 'RI', 'college', 'NCAA D1'),
  ('Seton Hall University', 'school', 'South Orange', 'NJ', 'college', 'NCAA D1'),
  ('St. John''s University', 'school', 'Queens', 'NY', 'college', 'NCAA D1'),
  ('Xavier University', 'school', 'Cincinnati', 'OH', 'college', 'NCAA D1'),
  -- Atlantic 10
  ('George Mason University', 'school', 'Fairfax', 'VA', 'college', 'NCAA D1'),
  ('George Washington University', 'school', 'Washington', 'DC', 'college', 'NCAA D1'),
  ('La Salle University', 'school', 'Philadelphia', 'PA', 'college', 'NCAA D1'),
  ('Loyola University Chicago', 'school', 'Chicago', 'IL', 'college', 'NCAA D1'),
  ('St. Bonaventure University', 'school', 'St. Bonaventure', 'NY', 'college', 'NCAA D1'),
  ('Saint Joseph''s University', 'school', 'Philadelphia', 'PA', 'college', 'NCAA D1'),
  ('Saint Louis University', 'school', 'St. Louis', 'MO', 'college', 'NCAA D1'),
  ('Virginia Commonwealth University', 'school', 'Richmond', 'VA', 'college', 'NCAA D1'),
  -- West Coast Conference
  ('Gonzaga University', 'school', 'Spokane', 'WA', 'college', 'NCAA D1'),
  ('Loyola Marymount University', 'school', 'Los Angeles', 'CA', 'college', 'NCAA D1'),
  ('University of the Pacific', 'school', 'Stockton', 'CA', 'college', 'NCAA D1'),
  ('Pepperdine University', 'school', 'Malibu', 'CA', 'college', 'NCAA D1'),
  ('University of Portland', 'school', 'Portland', 'OR', 'college', 'NCAA D1'),
  ('Saint Mary''s College of California', 'school', 'Moraga', 'CA', 'college', 'NCAA D1'),
  ('University of San Francisco', 'school', 'San Francisco', 'CA', 'college', 'NCAA D1'),
  ('Santa Clara University', 'school', 'Santa Clara', 'CA', 'college', 'NCAA D1'),
  ('Seattle University', 'school', 'Seattle', 'WA', 'college', 'NCAA D1'),
  -- WAC
  ('California Baptist University', 'school', 'Riverside', 'CA', 'college', 'NCAA D1'),
  ('Grand Canyon University', 'school', 'Phoenix', 'AZ', 'college', 'NCAA D1'),
  ('University of Texas at Arlington', 'school', 'Arlington', 'TX', 'college', 'NCAA D1'),
  ('Utah Valley University', 'school', 'Orem', 'UT', 'college', 'NCAA D1'),
  -- Horizon League
  ('Cleveland State University', 'school', 'Cleveland', 'OH', 'college', 'NCAA D1'),
  ('University of Detroit Mercy', 'school', 'Detroit', 'MI', 'college', 'NCAA D1'),
  ('University of Wisconsin-Green Bay', 'school', 'Green Bay', 'WI', 'college', 'NCAA D1'),
  ('Indiana University Indianapolis', 'school', 'Indianapolis', 'IN', 'college', 'NCAA D1'),
  ('University of Wisconsin-Milwaukee', 'school', 'Milwaukee', 'WI', 'college', 'NCAA D1'),
  ('Northern Kentucky University', 'school', 'Highland Heights', 'KY', 'college', 'NCAA D1'),
  ('Oakland University', 'school', 'Rochester', 'MI', 'college', 'NCAA D1'),
  ('Purdue University Fort Wayne', 'school', 'Fort Wayne', 'IN', 'college', 'NCAA D1'),
  ('Wright State University', 'school', 'Dayton', 'OH', 'college', 'NCAA D1'),
  -- MAAC
  ('Canisius University', 'school', 'Buffalo', 'NY', 'college', 'NCAA D1'),
  ('Fairfield University', 'school', 'Fairfield', 'CT', 'college', 'NCAA D1'),
  ('Iona University', 'school', 'New Rochelle', 'NY', 'college', 'NCAA D1'),
  ('Manhattan University', 'school', 'Riverdale', 'NY', 'college', 'NCAA D1'),
  ('Mount St. Mary''s University', 'school', 'Emmitsburg', 'MD', 'college', 'NCAA D1'),
  ('Niagara University', 'school', 'Lewiston', 'NY', 'college', 'NCAA D1'),
  ('Quinnipiac University', 'school', 'Hamden', 'CT', 'college', 'NCAA D1'),
  ('Rider University', 'school', 'Lawrenceville', 'NJ', 'college', 'NCAA D1'),
  ('Saint Peter''s University', 'school', 'Jersey City', 'NJ', 'college', 'NCAA D1'),
  ('Siena College', 'school', 'Loudonville', 'NY', 'college', 'NCAA D1'),
  -- America East
  ('Binghamton University', 'school', 'Binghamton', 'NY', 'college', 'NCAA D1'),
  ('New Jersey Institute of Technology', 'school', 'Newark', 'NJ', 'college', 'NCAA D1'),
  ('University of Maryland, Baltimore County', 'school', 'Baltimore', 'MD', 'college', 'NCAA D1'),
  ('University of Massachusetts Lowell', 'school', 'Lowell', 'MA', 'college', 'NCAA D1'),
  ('University of Vermont', 'school', 'Burlington', 'VT', 'college', 'NCAA D1'),
  -- ASUN
  ('Bellarmine University', 'school', 'Louisville', 'KY', 'college', 'NCAA D1'),
  ('Florida Gulf Coast University', 'school', 'Fort Myers', 'FL', 'college', 'NCAA D1'),
  ('Jacksonville University', 'school', 'Jacksonville', 'FL', 'college', 'NCAA D1'),
  ('Lipscomb University', 'school', 'Nashville', 'TN', 'college', 'NCAA D1'),
  ('University of North Florida', 'school', 'Jacksonville', 'FL', 'college', 'NCAA D1'),
  ('Queens University of Charlotte', 'school', 'Charlotte', 'NC', 'college', 'NCAA D1'),
  -- Big West
  ('California State University, Bakersfield', 'school', 'Bakersfield', 'CA', 'college', 'NCAA D1'),
  ('California State University, Fullerton', 'school', 'Fullerton', 'CA', 'college', 'NCAA D1'),
  ('California State University, Northridge', 'school', 'Northridge', 'CA', 'college', 'NCAA D1'),
  ('Long Beach State University', 'school', 'Long Beach', 'CA', 'college', 'NCAA D1'),
  ('University of California, Irvine', 'school', 'Irvine', 'CA', 'college', 'NCAA D1'),
  ('University of California, Riverside', 'school', 'Riverside', 'CA', 'college', 'NCAA D1'),
  ('University of California, San Diego', 'school', 'La Jolla', 'CA', 'college', 'NCAA D1'),
  ('University of California, Santa Barbara', 'school', 'Santa Barbara', 'CA', 'college', 'NCAA D1'),
  -- Missouri Valley Conference
  ('Belmont University', 'school', 'Nashville', 'TN', 'college', 'NCAA D1'),
  ('Bradley University', 'school', 'Peoria', 'IL', 'college', 'NCAA D1'),
  ('University of Evansville', 'school', 'Evansville', 'IN', 'college', 'NCAA D1'),
  ('University of Illinois Chicago', 'school', 'Chicago', 'IL', 'college', 'NCAA D1'),
  -- Ohio Valley Conference
  ('University of Arkansas at Little Rock', 'school', 'Little Rock', 'AR', 'college', 'NCAA D1'),
  ('Southern Illinois University Edwardsville', 'school', 'Edwardsville', 'IL', 'college', 'NCAA D1'),
  -- Southland (non-football)
  ('University of New Orleans', 'school', 'New Orleans', 'LA', 'college', 'NCAA D1'),
  ('Texas A&M University-Corpus Christi', 'school', 'Corpus Christi', 'TX', 'college', 'NCAA D1'),
  -- Summit League
  ('University of Denver', 'school', 'Denver', 'CO', 'college', 'NCAA D1'),
  ('University of Missouri-Kansas City', 'school', 'Kansas City', 'MO', 'college', 'NCAA D1'),
  ('University of Nebraska Omaha', 'school', 'Omaha', 'NE', 'college', 'NCAA D1'),
  ('Oral Roberts University', 'school', 'Tulsa', 'OK', 'college', 'NCAA D1'),
  -- Patriot League (non-football)
  ('American University', 'school', 'Washington', 'DC', 'college', 'NCAA D1'),
  ('Boston University', 'school', 'Boston', 'MA', 'college', 'NCAA D1'),
  ('Loyola University Maryland', 'school', 'Baltimore', 'MD', 'college', 'NCAA D1'),
  -- Big South (non-football)
  ('High Point University', 'school', 'High Point', 'NC', 'college', 'NCAA D1'),
  ('Longwood University', 'school', 'Farmville', 'VA', 'college', 'NCAA D1'),
  ('Radford University', 'school', 'Radford', 'VA', 'college', 'NCAA D1'),
  ('University of North Carolina at Asheville', 'school', 'Asheville', 'NC', 'college', 'NCAA D1'),
  ('University of South Carolina Upstate', 'school', 'Spartanburg', 'SC', 'college', 'NCAA D1'),
  ('Winthrop University', 'school', 'Rock Hill', 'SC', 'college', 'NCAA D1'),
  -- Northeast Conference (non-football)
  ('Chicago State University', 'school', 'Chicago', 'IL', 'college', 'NCAA D1'),
  ('Fairleigh Dickinson University', 'school', 'Teaneck', 'NJ', 'college', 'NCAA D1'),
  ('Le Moyne College', 'school', 'Syracuse', 'NY', 'college', 'NCAA D1'),
  -- MEAC (non-football)
  ('Coppin State University', 'school', 'Baltimore', 'MD', 'college', 'NCAA D1'),
  ('University of Maryland Eastern Shore', 'school', 'Princess Anne', 'MD', 'college', 'NCAA D1'),
  -- American (non-football)
  ('Wichita State University', 'school', 'Wichita', 'KS', 'college', 'NCAA D1'),
  -- CAA (non-football)
  ('College of Charleston', 'school', 'Charleston', 'SC', 'college', 'NCAA D1'),
  ('Drexel University', 'school', 'Philadelphia', 'PA', 'college', 'NCAA D1'),
  ('Hofstra University', 'school', 'Hempstead', 'NY', 'college', 'NCAA D1'),
  ('Northeastern University', 'school', 'Boston', 'MA', 'college', 'NCAA D1'),
  ('University of North Carolina Wilmington', 'school', 'Wilmington', 'NC', 'college', 'NCAA D1'),
  -- Southern Conference (non-football)
  ('University of North Carolina at Greensboro', 'school', 'Greensboro', 'NC', 'college', 'NCAA D1')
on conflict ((lower(name)), (coalesce(state, ''))) where created_by is null do nothing;

-- ================================================================ NFL (32)
insert into orgs (name, type, city, state, level, league) values
  ('Arizona Cardinals', 'club', 'Glendale', 'AZ', 'pro', 'NFL'),
  ('Atlanta Falcons', 'club', 'Atlanta', 'GA', 'pro', 'NFL'),
  ('Baltimore Ravens', 'club', 'Baltimore', 'MD', 'pro', 'NFL'),
  ('Buffalo Bills', 'club', 'Orchard Park', 'NY', 'pro', 'NFL'),
  ('Carolina Panthers', 'club', 'Charlotte', 'NC', 'pro', 'NFL'),
  ('Chicago Bears', 'club', 'Chicago', 'IL', 'pro', 'NFL'),
  ('Cincinnati Bengals', 'club', 'Cincinnati', 'OH', 'pro', 'NFL'),
  ('Cleveland Browns', 'club', 'Cleveland', 'OH', 'pro', 'NFL'),
  ('Dallas Cowboys', 'club', 'Arlington', 'TX', 'pro', 'NFL'),
  ('Denver Broncos', 'club', 'Denver', 'CO', 'pro', 'NFL'),
  ('Detroit Lions', 'club', 'Detroit', 'MI', 'pro', 'NFL'),
  ('Green Bay Packers', 'club', 'Green Bay', 'WI', 'pro', 'NFL'),
  ('Houston Texans', 'club', 'Houston', 'TX', 'pro', 'NFL'),
  ('Indianapolis Colts', 'club', 'Indianapolis', 'IN', 'pro', 'NFL'),
  ('Jacksonville Jaguars', 'club', 'Jacksonville', 'FL', 'pro', 'NFL'),
  ('Kansas City Chiefs', 'club', 'Kansas City', 'MO', 'pro', 'NFL'),
  ('Las Vegas Raiders', 'club', 'Las Vegas', 'NV', 'pro', 'NFL'),
  ('Los Angeles Chargers', 'club', 'Inglewood', 'CA', 'pro', 'NFL'),
  ('Los Angeles Rams', 'club', 'Inglewood', 'CA', 'pro', 'NFL'),
  ('Miami Dolphins', 'club', 'Miami Gardens', 'FL', 'pro', 'NFL'),
  ('Minnesota Vikings', 'club', 'Minneapolis', 'MN', 'pro', 'NFL'),
  ('New England Patriots', 'club', 'Foxborough', 'MA', 'pro', 'NFL'),
  ('New Orleans Saints', 'club', 'New Orleans', 'LA', 'pro', 'NFL'),
  ('New York Giants', 'club', 'East Rutherford', 'NJ', 'pro', 'NFL'),
  ('New York Jets', 'club', 'East Rutherford', 'NJ', 'pro', 'NFL'),
  ('Philadelphia Eagles', 'club', 'Philadelphia', 'PA', 'pro', 'NFL'),
  ('Pittsburgh Steelers', 'club', 'Pittsburgh', 'PA', 'pro', 'NFL'),
  ('San Francisco 49ers', 'club', 'Santa Clara', 'CA', 'pro', 'NFL'),
  ('Seattle Seahawks', 'club', 'Seattle', 'WA', 'pro', 'NFL'),
  ('Tampa Bay Buccaneers', 'club', 'Tampa', 'FL', 'pro', 'NFL'),
  ('Tennessee Titans', 'club', 'Nashville', 'TN', 'pro', 'NFL'),
  ('Washington Commanders', 'club', 'Landover', 'MD', 'pro', 'NFL')
on conflict ((lower(name)), (coalesce(state, ''))) where created_by is null do nothing;

-- ================================================================ NBA (30)
insert into orgs (name, type, city, state, level, league) values
  ('Atlanta Hawks', 'club', 'Atlanta', 'GA', 'pro', 'NBA'),
  ('Boston Celtics', 'club', 'Boston', 'MA', 'pro', 'NBA'),
  ('Brooklyn Nets', 'club', 'Brooklyn', 'NY', 'pro', 'NBA'),
  ('Charlotte Hornets', 'club', 'Charlotte', 'NC', 'pro', 'NBA'),
  ('Chicago Bulls', 'club', 'Chicago', 'IL', 'pro', 'NBA'),
  ('Cleveland Cavaliers', 'club', 'Cleveland', 'OH', 'pro', 'NBA'),
  ('Dallas Mavericks', 'club', 'Dallas', 'TX', 'pro', 'NBA'),
  ('Denver Nuggets', 'club', 'Denver', 'CO', 'pro', 'NBA'),
  ('Detroit Pistons', 'club', 'Detroit', 'MI', 'pro', 'NBA'),
  ('Golden State Warriors', 'club', 'San Francisco', 'CA', 'pro', 'NBA'),
  ('Houston Rockets', 'club', 'Houston', 'TX', 'pro', 'NBA'),
  ('Indiana Pacers', 'club', 'Indianapolis', 'IN', 'pro', 'NBA'),
  ('Los Angeles Clippers', 'club', 'Inglewood', 'CA', 'pro', 'NBA'),
  ('Los Angeles Lakers', 'club', 'Los Angeles', 'CA', 'pro', 'NBA'),
  ('Memphis Grizzlies', 'club', 'Memphis', 'TN', 'pro', 'NBA'),
  ('Miami Heat', 'club', 'Miami', 'FL', 'pro', 'NBA'),
  ('Milwaukee Bucks', 'club', 'Milwaukee', 'WI', 'pro', 'NBA'),
  ('Minnesota Timberwolves', 'club', 'Minneapolis', 'MN', 'pro', 'NBA'),
  ('New Orleans Pelicans', 'club', 'New Orleans', 'LA', 'pro', 'NBA'),
  ('New York Knicks', 'club', 'New York', 'NY', 'pro', 'NBA'),
  ('Oklahoma City Thunder', 'club', 'Oklahoma City', 'OK', 'pro', 'NBA'),
  ('Orlando Magic', 'club', 'Orlando', 'FL', 'pro', 'NBA'),
  ('Philadelphia 76ers', 'club', 'Philadelphia', 'PA', 'pro', 'NBA'),
  ('Phoenix Suns', 'club', 'Phoenix', 'AZ', 'pro', 'NBA'),
  ('Portland Trail Blazers', 'club', 'Portland', 'OR', 'pro', 'NBA'),
  ('Sacramento Kings', 'club', 'Sacramento', 'CA', 'pro', 'NBA'),
  ('San Antonio Spurs', 'club', 'San Antonio', 'TX', 'pro', 'NBA'),
  ('Toronto Raptors', 'club', 'Toronto', 'ON', 'pro', 'NBA'),
  ('Utah Jazz', 'club', 'Salt Lake City', 'UT', 'pro', 'NBA'),
  ('Washington Wizards', 'club', 'Washington', 'DC', 'pro', 'NBA')
on conflict ((lower(name)), (coalesce(state, ''))) where created_by is null do nothing;

-- ================================================================ MLB (30)
insert into orgs (name, type, city, state, level, league) values
  ('Arizona Diamondbacks', 'club', 'Phoenix', 'AZ', 'pro', 'MLB'),
  ('Athletics', 'club', 'West Sacramento', 'CA', 'pro', 'MLB'),
  ('Atlanta Braves', 'club', 'Atlanta', 'GA', 'pro', 'MLB'),
  ('Baltimore Orioles', 'club', 'Baltimore', 'MD', 'pro', 'MLB'),
  ('Boston Red Sox', 'club', 'Boston', 'MA', 'pro', 'MLB'),
  ('Chicago Cubs', 'club', 'Chicago', 'IL', 'pro', 'MLB'),
  ('Chicago White Sox', 'club', 'Chicago', 'IL', 'pro', 'MLB'),
  ('Cincinnati Reds', 'club', 'Cincinnati', 'OH', 'pro', 'MLB'),
  ('Cleveland Guardians', 'club', 'Cleveland', 'OH', 'pro', 'MLB'),
  ('Colorado Rockies', 'club', 'Denver', 'CO', 'pro', 'MLB'),
  ('Detroit Tigers', 'club', 'Detroit', 'MI', 'pro', 'MLB'),
  ('Houston Astros', 'club', 'Houston', 'TX', 'pro', 'MLB'),
  ('Kansas City Royals', 'club', 'Kansas City', 'MO', 'pro', 'MLB'),
  ('Los Angeles Angels', 'club', 'Anaheim', 'CA', 'pro', 'MLB'),
  ('Los Angeles Dodgers', 'club', 'Los Angeles', 'CA', 'pro', 'MLB'),
  ('Miami Marlins', 'club', 'Miami', 'FL', 'pro', 'MLB'),
  ('Milwaukee Brewers', 'club', 'Milwaukee', 'WI', 'pro', 'MLB'),
  ('Minnesota Twins', 'club', 'Minneapolis', 'MN', 'pro', 'MLB'),
  ('New York Mets', 'club', 'Queens', 'NY', 'pro', 'MLB'),
  ('New York Yankees', 'club', 'Bronx', 'NY', 'pro', 'MLB'),
  ('Philadelphia Phillies', 'club', 'Philadelphia', 'PA', 'pro', 'MLB'),
  ('Pittsburgh Pirates', 'club', 'Pittsburgh', 'PA', 'pro', 'MLB'),
  ('San Diego Padres', 'club', 'San Diego', 'CA', 'pro', 'MLB'),
  ('San Francisco Giants', 'club', 'San Francisco', 'CA', 'pro', 'MLB'),
  ('Seattle Mariners', 'club', 'Seattle', 'WA', 'pro', 'MLB'),
  ('St. Louis Cardinals', 'club', 'St. Louis', 'MO', 'pro', 'MLB'),
  ('Tampa Bay Rays', 'club', 'St. Petersburg', 'FL', 'pro', 'MLB'),
  ('Texas Rangers', 'club', 'Arlington', 'TX', 'pro', 'MLB'),
  ('Toronto Blue Jays', 'club', 'Toronto', 'ON', 'pro', 'MLB'),
  ('Washington Nationals', 'club', 'Washington', 'DC', 'pro', 'MLB')
on conflict ((lower(name)), (coalesce(state, ''))) where created_by is null do nothing;

-- ================================================================ NHL (32)
insert into orgs (name, type, city, state, level, league) values
  ('Anaheim Ducks', 'club', 'Anaheim', 'CA', 'pro', 'NHL'),
  ('Boston Bruins', 'club', 'Boston', 'MA', 'pro', 'NHL'),
  ('Buffalo Sabres', 'club', 'Buffalo', 'NY', 'pro', 'NHL'),
  ('Calgary Flames', 'club', 'Calgary', 'AB', 'pro', 'NHL'),
  ('Carolina Hurricanes', 'club', 'Raleigh', 'NC', 'pro', 'NHL'),
  ('Chicago Blackhawks', 'club', 'Chicago', 'IL', 'pro', 'NHL'),
  ('Colorado Avalanche', 'club', 'Denver', 'CO', 'pro', 'NHL'),
  ('Columbus Blue Jackets', 'club', 'Columbus', 'OH', 'pro', 'NHL'),
  ('Dallas Stars', 'club', 'Dallas', 'TX', 'pro', 'NHL'),
  ('Detroit Red Wings', 'club', 'Detroit', 'MI', 'pro', 'NHL'),
  ('Edmonton Oilers', 'club', 'Edmonton', 'AB', 'pro', 'NHL'),
  ('Florida Panthers', 'club', 'Sunrise', 'FL', 'pro', 'NHL'),
  ('Los Angeles Kings', 'club', 'Los Angeles', 'CA', 'pro', 'NHL'),
  ('Minnesota Wild', 'club', 'St. Paul', 'MN', 'pro', 'NHL'),
  ('Montreal Canadiens', 'club', 'Montreal', 'QC', 'pro', 'NHL'),
  ('Nashville Predators', 'club', 'Nashville', 'TN', 'pro', 'NHL'),
  ('New Jersey Devils', 'club', 'Newark', 'NJ', 'pro', 'NHL'),
  ('New York Islanders', 'club', 'Elmont', 'NY', 'pro', 'NHL'),
  ('New York Rangers', 'club', 'New York', 'NY', 'pro', 'NHL'),
  ('Ottawa Senators', 'club', 'Ottawa', 'ON', 'pro', 'NHL'),
  ('Philadelphia Flyers', 'club', 'Philadelphia', 'PA', 'pro', 'NHL'),
  ('Pittsburgh Penguins', 'club', 'Pittsburgh', 'PA', 'pro', 'NHL'),
  ('San Jose Sharks', 'club', 'San Jose', 'CA', 'pro', 'NHL'),
  ('Seattle Kraken', 'club', 'Seattle', 'WA', 'pro', 'NHL'),
  ('St. Louis Blues', 'club', 'St. Louis', 'MO', 'pro', 'NHL'),
  ('Tampa Bay Lightning', 'club', 'Tampa', 'FL', 'pro', 'NHL'),
  ('Toronto Maple Leafs', 'club', 'Toronto', 'ON', 'pro', 'NHL'),
  ('Utah Mammoth', 'club', 'Salt Lake City', 'UT', 'pro', 'NHL'),
  ('Vancouver Canucks', 'club', 'Vancouver', 'BC', 'pro', 'NHL'),
  ('Vegas Golden Knights', 'club', 'Las Vegas', 'NV', 'pro', 'NHL'),
  ('Washington Capitals', 'club', 'Washington', 'DC', 'pro', 'NHL'),
  ('Winnipeg Jets', 'club', 'Winnipeg', 'MB', 'pro', 'NHL')
on conflict ((lower(name)), (coalesce(state, ''))) where created_by is null do nothing;

-- ================================================================ MLS (30)
insert into orgs (name, type, city, state, level, league) values
  ('Atlanta United FC', 'club', 'Atlanta', 'GA', 'pro', 'MLS'),
  ('Austin FC', 'club', 'Austin', 'TX', 'pro', 'MLS'),
  ('CF Montreal', 'club', 'Montreal', 'QC', 'pro', 'MLS'),
  ('Charlotte FC', 'club', 'Charlotte', 'NC', 'pro', 'MLS'),
  ('Chicago Fire FC', 'club', 'Chicago', 'IL', 'pro', 'MLS'),
  ('FC Cincinnati', 'club', 'Cincinnati', 'OH', 'pro', 'MLS'),
  ('Colorado Rapids', 'club', 'Commerce City', 'CO', 'pro', 'MLS'),
  ('Columbus Crew', 'club', 'Columbus', 'OH', 'pro', 'MLS'),
  ('FC Dallas', 'club', 'Frisco', 'TX', 'pro', 'MLS'),
  ('D.C. United', 'club', 'Washington', 'DC', 'pro', 'MLS'),
  ('Houston Dynamo FC', 'club', 'Houston', 'TX', 'pro', 'MLS'),
  ('Inter Miami CF', 'club', 'Fort Lauderdale', 'FL', 'pro', 'MLS'),
  ('LA Galaxy', 'club', 'Carson', 'CA', 'pro', 'MLS'),
  ('Los Angeles FC', 'club', 'Los Angeles', 'CA', 'pro', 'MLS'),
  ('Minnesota United FC', 'club', 'St. Paul', 'MN', 'pro', 'MLS'),
  ('Nashville SC', 'club', 'Nashville', 'TN', 'pro', 'MLS'),
  ('New England Revolution', 'club', 'Foxborough', 'MA', 'pro', 'MLS'),
  ('New York City FC', 'club', 'New York', 'NY', 'pro', 'MLS'),
  ('New York Red Bulls', 'club', 'Harrison', 'NJ', 'pro', 'MLS'),
  ('Orlando City SC', 'club', 'Orlando', 'FL', 'pro', 'MLS'),
  ('Philadelphia Union', 'club', 'Chester', 'PA', 'pro', 'MLS'),
  ('Portland Timbers', 'club', 'Portland', 'OR', 'pro', 'MLS'),
  ('Real Salt Lake', 'club', 'Sandy', 'UT', 'pro', 'MLS'),
  ('San Diego FC', 'club', 'San Diego', 'CA', 'pro', 'MLS'),
  ('San Jose Earthquakes', 'club', 'San Jose', 'CA', 'pro', 'MLS'),
  ('Seattle Sounders FC', 'club', 'Seattle', 'WA', 'pro', 'MLS'),
  ('Sporting Kansas City', 'club', 'Kansas City', 'KS', 'pro', 'MLS'),
  ('St. Louis City SC', 'club', 'St. Louis', 'MO', 'pro', 'MLS'),
  ('Toronto FC', 'club', 'Toronto', 'ON', 'pro', 'MLS'),
  ('Vancouver Whitecaps FC', 'club', 'Vancouver', 'BC', 'pro', 'MLS')
on conflict ((lower(name)), (coalesce(state, ''))) where created_by is null do nothing;
